FROM node:14
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 8080
ENV PORT=8080
ENV MONGODB_CNN=
ENV SENDGRID_API_KEY=
ENV SENDGRID_FROM_EMAIL=
ENV SECRET_KEY_JWT=
ENV FRONT_END_URL=
CMD ["npm", "start"]
